services:

  postgres:
    image: postgres:alpine
    container_name: minhasfinancas_postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - minhasfinancas

volumes:
  postgres-db:
    external: true

networks:
  minhasfinancas:
    external: true