services:

  postgres:
    image: postgres:alpine
    container_name: minhasfinancas_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - minhasfinancas

  java_app:
    image: minhasfinancas:${APP_VERSION}
    container_name: java_app
    build: .
    environment:
      - DB_HOST=jdbc:postgresql://postgres:5432/minhasfinancas
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 9000:9000
    depends_on:
      - postgres
    networks:
      - minhasfinancas

volumes:
  postgres-db:
    external: true

networks:
  minhasfinancas:
    external: true